In [4]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve
import pandas as pd
from kloppy import secondspectrum

In [3]:
import sys
 
# setting path
sys.path.append('../')
 
# importing
from src import Metrica_PitchControl01

In [6]:

dataset = secondspectrum.load(
    meta_data="../man-city-data/SecondSpectrum/MCI Women_s Files-001/g2312135_SecondSpectrum_meta.xml",
    raw_data="../man-city-data/SecondSpectrum/MCI Women_s Files-001/g2312135_SecondSpectrum_tracking-produced.jsonl",
    
    # Optional arguments
    sample_rate=1/1,
    coordinates="secondspectrum",
    only_alive=True)

df = dataset.to_df()

In [7]:
df.shape

(85502, 120)

In [8]:
df.head()

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,0746befc-a701-4b33-8faf-b3cccccf17bb_x,0746befc-a701-4b33-8faf-b3cccccf17bb_y,...,2c5def63-7238-4ca2-aa32-5ccbabe5a0b0_d,2c5def63-7238-4ca2-aa32-5ccbabe5a0b0_s,f7ae46be-3ace-423d-bee0-3482b314eb2e_x,f7ae46be-3ace-423d-bee0-3482b314eb2e_y,f7ae46be-3ace-423d-bee0-3482b314eb2e_d,f7ae46be-3ace-423d-bee0-3482b314eb2e_s,87dbfea7-b4c1-49ce-b210-6210f5efae55_x,87dbfea7-b4c1-49ce-b210-6210f5efae55_y,87dbfea7-b4c1-49ce-b210-6210f5efae55_d,87dbfea7-b4c1-49ce-b210-6210f5efae55_s
0,1,0.04,1,alive,home,-0.82,0.22,0.28,-11.08,1.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0.08,2,alive,home,-1.34,0.30,0.28,-11.07,1.59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0.12,3,alive,home,-1.80,0.41,0.28,-11.07,1.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,0.16,4,alive,home,-2.29,0.51,0.28,-11.05,1.63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,0.20,5,alive,home,-2.74,0.61,0.28,-11.04,1.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df.filter(regex='^(.*)(_d|_s)$')

In [11]:
df.shape

(85502, 56)

In [26]:
h,a = dataset.metadata.teams

In [30]:
for p in a.players:
    print(p.player_id)

092fcb72-e828-4d76-b7b9-abdf8c0d07ad
16bae841-2083-41fa-a659-031ee07d867d
2b4f2f32-87cb-4cc7-bf6c-211f5ad1242a
5551eb44-290b-426d-9311-8154e778d407
5ee28902-a961-4cbc-855e-84e4af865a70
8b2decb4-3722-4313-b0a0-d0a48e39aeb2
a63bc99a-6a68-4934-9a17-d4117c810085
c7598a8f-b910-46a7-8ee3-c052c228ceff
d588cf67-0e75-4619-a541-d0945138b3fb
e8b086da-181d-4404-9e80-bf4b0035e2ec
f3a6c7a6-4686-4c77-8e87-5bd842ec1642
8446653e-8da9-44b1-9b01-2cc7fd19481b
dc64b316-4b36-4467-838c-96bcbc242748
bea130d3-e02f-4d51-b301-2ef18a880a95
2c5def63-7238-4ca2-aa32-5ccbabe5a0b0
f7ae46be-3ace-423d-bee0-3482b314eb2e

In [ ]:
columns_to_keep = [col for col in df.columns if any(s in col for s in other_strings)]
df = df[columns_to_keep]